
export const ErrorCodes = {
    AUTHORIZATION_FAILED: 0,
    CONNECTOR_OPERATION_FAILED: 10,
    ENTITY_ALREADY_EXISTS: 20,
    HOST_NOT_REACHED: 30,
    INSUFFICIENT_STORAGE: 40,
    INVALID_QUERY: 50,
    MISCONFIGURED_SYSTEM: 60,
    MISSING_DECORATOR: 70,
    NO_BINARY_CONTENT: 80,
    NO_SUCH_ENTITY: 90,
    NO_SUCH_HANDLER: 100,
    NO_SUCH_SCOPE: 110,
    OPERATION_NOT_ALLOWED: 120,
    QUOTA_EXCEEDED: 130,
    UNSUPPORTED_CONTENT_TYPE: 140,
    INVALID_CONFIGURATION: 150
};
